// This file is @generated by prost-build.
#[allow(dead_code)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Empty {}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct User {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub is_admin: bool,
    #[prost(bool, tag = "5")]
    pub totp_enabled: bool,
    #[prost(bool, tag = "6")]
    pub require_2fa: bool,
    #[prost(string, tag = "7")]
    pub created_at: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthResponse {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub refresh_token: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub user: ::core::option::Option<User>,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterRequest {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub password: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginRequest {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RefreshRequest {
    #[prost(string, tag = "1")]
    pub refresh_token: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdatePasswordRequest {
    #[prost(string, tag = "1")]
    pub current_password: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub new_password: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Setup2FaResponse {
    #[prost(string, tag = "1")]
    pub secret: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub qr_code: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Verify2FaRequest {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Enable2FaRequest {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Disable2FaRequest {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BackupCodesResponse {
    #[prost(string, repeated, tag = "1")]
    pub codes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[allow(dead_code)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListUsersRequest {
    #[prost(int32, tag = "1")]
    pub page: i32,
    #[prost(int32, tag = "2")]
    pub page_size: i32,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListUsersResponse {
    #[prost(message, repeated, tag = "1")]
    pub users: ::prost::alloc::vec::Vec<User>,
    #[prost(int32, tag = "2")]
    pub total: i32,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateUserRequest {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub password: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub is_admin: bool,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateUserRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub username: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub email: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bool, optional, tag = "4")]
    pub disabled: ::core::option::Option<bool>,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetAdminRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_admin: bool,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Ack {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileMetadata {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub original_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub mime_type: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub size_bytes: i64,
    #[prost(string, tag = "5")]
    pub uploader_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub uploaded_at: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Chat {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_group: bool,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub participants: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "5")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub created_by: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub is_favorites: bool,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub chat_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub sender_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub encrypted_content: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub content_type: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub file_metadata_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub status: ::prost::alloc::string::String,
    #[prost(bool, tag = "8")]
    pub edited: bool,
    #[prost(bool, tag = "9")]
    pub deleted: bool,
    #[prost(string, tag = "10")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub edited_at: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub topic_id: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub thread_id: ::prost::alloc::string::String,
}
