// This file is @generated by prost-build.
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSfuConfigRequest {
    #[prost(string, tag = "1")]
    pub chat_id: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CallRequest {
    #[prost(string, tag = "1")]
    pub callee_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub chat_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub sdp_offer: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CallEvent {
    #[prost(oneof = "call_event::Event", tags = "1, 2, 3, 4, 5, 6")]
    pub event: ::core::option::Option<call_event::Event>,
}
/// Nested message and enum types in `CallEvent`.
pub mod call_event {
    #[allow(dead_code)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Ringing {
        #[prost(string, tag = "1")]
        pub call_id: ::prost::alloc::string::String,
    }
    #[allow(dead_code)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Accepted {
        #[prost(string, tag = "1")]
        pub call_id: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub sdp_offer: ::prost::alloc::string::String,
    }
    #[allow(dead_code)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Answer {
        #[prost(string, tag = "1")]
        pub call_id: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub sdp_answer: ::prost::alloc::string::String,
    }
    #[allow(dead_code)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct IceCandidate {
        #[prost(string, tag = "1")]
        pub call_id: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub candidate: ::prost::alloc::string::String,
    }
    #[allow(dead_code)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Ended {
        #[prost(string, tag = "1")]
        pub call_id: ::prost::alloc::string::String,
    }
    #[allow(dead_code)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Declined {
        #[prost(string, tag = "1")]
        pub call_id: ::prost::alloc::string::String,
    }
    #[allow(dead_code)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "1")]
        Ringing(Ringing),
        #[prost(message, tag = "2")]
        Accepted(Accepted),
        #[prost(message, tag = "3")]
        Answer(Answer),
        #[prost(message, tag = "4")]
        IceCandidate(IceCandidate),
        #[prost(message, tag = "5")]
        Ended(Ended),
        #[prost(message, tag = "6")]
        Declined(Declined),
    }
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AcceptCallRequest {
    #[prost(string, tag = "1")]
    pub call_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub sdp_answer: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeclineCallRequest {
    #[prost(string, tag = "1")]
    pub call_id: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CallEndRequest {
    #[prost(string, tag = "1")]
    pub call_id: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IceCandidate {
    #[prost(string, tag = "1")]
    pub call_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub candidate: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JoinGroupCallRequest {
    #[prost(string, tag = "1")]
    pub chat_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub sdp_offer: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupCallEvent {
    #[prost(oneof = "group_call_event::Event", tags = "1, 2, 3, 4")]
    pub event: ::core::option::Option<group_call_event::Event>,
}
/// Nested message and enum types in `GroupCallEvent`.
pub mod group_call_event {
    #[allow(dead_code)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ParticipantJoined {
        #[prost(string, tag = "1")]
        pub call_id: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub user_id: ::prost::alloc::string::String,
        #[prost(string, tag = "3")]
        pub sdp_offer: ::prost::alloc::string::String,
    }
    #[allow(dead_code)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ParticipantAnswered {
        #[prost(string, tag = "1")]
        pub call_id: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub user_id: ::prost::alloc::string::String,
        #[prost(string, tag = "3")]
        pub sdp_answer: ::prost::alloc::string::String,
    }
    #[allow(dead_code)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ParticipantIce {
        #[prost(string, tag = "1")]
        pub call_id: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub user_id: ::prost::alloc::string::String,
        #[prost(string, tag = "3")]
        pub candidate: ::prost::alloc::string::String,
    }
    #[allow(dead_code)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct ParticipantLeft {
        #[prost(string, tag = "1")]
        pub call_id: ::prost::alloc::string::String,
        #[prost(string, tag = "2")]
        pub user_id: ::prost::alloc::string::String,
    }
    #[allow(dead_code)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "1")]
        ParticipantJoined(ParticipantJoined),
        #[prost(message, tag = "2")]
        ParticipantAnswered(ParticipantAnswered),
        #[prost(message, tag = "3")]
        ParticipantIce(ParticipantIce),
        #[prost(message, tag = "4")]
        ParticipantLeft(ParticipantLeft),
    }
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LeaveGroupCallRequest {
    #[prost(string, tag = "1")]
    pub call_id: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SfuConfig {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub ice_servers: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Generated client implementations.
pub mod signaling_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct SignalingClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl SignalingClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> SignalingClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> SignalingClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            SignalingClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn call_user(
            &mut self,
            request: impl tonic::IntoRequest<super::CallRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::CallEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/signaling.Signaling/CallUser",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("signaling.Signaling", "CallUser"));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn accept_call(
            &mut self,
            request: impl tonic::IntoRequest<super::AcceptCallRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/signaling.Signaling/AcceptCall",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("signaling.Signaling", "AcceptCall"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn decline_call(
            &mut self,
            request: impl tonic::IntoRequest<super::DeclineCallRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/signaling.Signaling/DeclineCall",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("signaling.Signaling", "DeclineCall"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn end_call(
            &mut self,
            request: impl tonic::IntoRequest<super::CallEndRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/signaling.Signaling/EndCall",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("signaling.Signaling", "EndCall"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn ice_candidate(
            &mut self,
            request: impl tonic::IntoRequest<super::IceCandidate>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/signaling.Signaling/IceCandidate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("signaling.Signaling", "IceCandidate"));
            self.inner.unary(req, path, codec).await
        }
        /// Group calls
        pub async fn join_group_call(
            &mut self,
            request: impl tonic::IntoRequest<super::JoinGroupCallRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::GroupCallEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/signaling.Signaling/JoinGroupCall",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("signaling.Signaling", "JoinGroupCall"));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn leave_group_call(
            &mut self,
            request: impl tonic::IntoRequest<super::LeaveGroupCallRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/signaling.Signaling/LeaveGroupCall",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("signaling.Signaling", "LeaveGroupCall"));
            self.inner.unary(req, path, codec).await
        }
        /// SFU configuration for group calls
        pub async fn get_sfu_config(
            &mut self,
            request: impl tonic::IntoRequest<super::GetSfuConfigRequest>,
        ) -> std::result::Result<tonic::Response<super::SfuConfig>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/signaling.Signaling/GetSfuConfig",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("signaling.Signaling", "GetSfuConfig"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod signaling_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with SignalingServer.
    #[async_trait]
    pub trait Signaling: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the CallUser method.
        type CallUserStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::CallEvent, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn call_user(
            &self,
            request: tonic::Request<super::CallRequest>,
        ) -> std::result::Result<tonic::Response<Self::CallUserStream>, tonic::Status>;
        async fn accept_call(
            &self,
            request: tonic::Request<super::AcceptCallRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        >;
        async fn decline_call(
            &self,
            request: tonic::Request<super::DeclineCallRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        >;
        async fn end_call(
            &self,
            request: tonic::Request<super::CallEndRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        >;
        async fn ice_candidate(
            &self,
            request: tonic::Request<super::IceCandidate>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        >;
        /// Server streaming response type for the JoinGroupCall method.
        type JoinGroupCallStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::GroupCallEvent, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Group calls
        async fn join_group_call(
            &self,
            request: tonic::Request<super::JoinGroupCallRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::JoinGroupCallStream>,
            tonic::Status,
        >;
        async fn leave_group_call(
            &self,
            request: tonic::Request<super::LeaveGroupCallRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        >;
        /// SFU configuration for group calls
        async fn get_sfu_config(
            &self,
            request: tonic::Request<super::GetSfuConfigRequest>,
        ) -> std::result::Result<tonic::Response<super::SfuConfig>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct SignalingServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> SignalingServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for SignalingServer<T>
    where
        T: Signaling,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/signaling.Signaling/CallUser" => {
                    #[allow(non_camel_case_types)]
                    struct CallUserSvc<T: Signaling>(pub Arc<T>);
                    impl<
                        T: Signaling,
                    > tonic::server::ServerStreamingService<super::CallRequest>
                    for CallUserSvc<T> {
                        type Response = super::CallEvent;
                        type ResponseStream = T::CallUserStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CallRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Signaling>::call_user(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CallUserSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/signaling.Signaling/AcceptCall" => {
                    #[allow(non_camel_case_types)]
                    struct AcceptCallSvc<T: Signaling>(pub Arc<T>);
                    impl<
                        T: Signaling,
                    > tonic::server::UnaryService<super::AcceptCallRequest>
                    for AcceptCallSvc<T> {
                        type Response = super::super::common::Ack;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AcceptCallRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Signaling>::accept_call(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AcceptCallSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/signaling.Signaling/DeclineCall" => {
                    #[allow(non_camel_case_types)]
                    struct DeclineCallSvc<T: Signaling>(pub Arc<T>);
                    impl<
                        T: Signaling,
                    > tonic::server::UnaryService<super::DeclineCallRequest>
                    for DeclineCallSvc<T> {
                        type Response = super::super::common::Ack;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeclineCallRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Signaling>::decline_call(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeclineCallSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/signaling.Signaling/EndCall" => {
                    #[allow(non_camel_case_types)]
                    struct EndCallSvc<T: Signaling>(pub Arc<T>);
                    impl<T: Signaling> tonic::server::UnaryService<super::CallEndRequest>
                    for EndCallSvc<T> {
                        type Response = super::super::common::Ack;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CallEndRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Signaling>::end_call(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = EndCallSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/signaling.Signaling/IceCandidate" => {
                    #[allow(non_camel_case_types)]
                    struct IceCandidateSvc<T: Signaling>(pub Arc<T>);
                    impl<T: Signaling> tonic::server::UnaryService<super::IceCandidate>
                    for IceCandidateSvc<T> {
                        type Response = super::super::common::Ack;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::IceCandidate>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Signaling>::ice_candidate(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = IceCandidateSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/signaling.Signaling/JoinGroupCall" => {
                    #[allow(non_camel_case_types)]
                    struct JoinGroupCallSvc<T: Signaling>(pub Arc<T>);
                    impl<
                        T: Signaling,
                    > tonic::server::ServerStreamingService<super::JoinGroupCallRequest>
                    for JoinGroupCallSvc<T> {
                        type Response = super::GroupCallEvent;
                        type ResponseStream = T::JoinGroupCallStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::JoinGroupCallRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Signaling>::join_group_call(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = JoinGroupCallSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/signaling.Signaling/LeaveGroupCall" => {
                    #[allow(non_camel_case_types)]
                    struct LeaveGroupCallSvc<T: Signaling>(pub Arc<T>);
                    impl<
                        T: Signaling,
                    > tonic::server::UnaryService<super::LeaveGroupCallRequest>
                    for LeaveGroupCallSvc<T> {
                        type Response = super::super::common::Ack;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LeaveGroupCallRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Signaling>::leave_group_call(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LeaveGroupCallSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/signaling.Signaling/GetSfuConfig" => {
                    #[allow(non_camel_case_types)]
                    struct GetSfuConfigSvc<T: Signaling>(pub Arc<T>);
                    impl<
                        T: Signaling,
                    > tonic::server::UnaryService<super::GetSfuConfigRequest>
                    for GetSfuConfigSvc<T> {
                        type Response = super::SfuConfig;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetSfuConfigRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Signaling>::get_sfu_config(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetSfuConfigSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for SignalingServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "signaling.Signaling";
    impl<T> tonic::server::NamedService for SignalingServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
