// This file is @generated by prost-build.
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Chat {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_group: bool,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub participants: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "5")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub created_by: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub is_favorites: bool,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub chat_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub sender_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub encrypted_content: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub content_type: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub file_metadata_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub status: ::prost::alloc::string::String,
    #[prost(bool, tag = "8")]
    pub edited: bool,
    #[prost(bool, tag = "9")]
    pub deleted: bool,
    #[prost(string, tag = "10")]
    pub created_at: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub edited_at: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub topic_id: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub thread_id: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FileMetadata {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub original_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub mime_type: ::prost::alloc::string::String,
    #[prost(int64, tag = "4")]
    pub size_bytes: i64,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessagesPage {
    #[prost(message, repeated, tag = "1")]
    pub messages: ::prost::alloc::vec::Vec<Message>,
    #[prost(string, tag = "2")]
    pub next_cursor: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub has_more: bool,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateChatRequest {
    #[prost(string, repeated, tag = "1")]
    pub participants: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "2")]
    pub is_group: bool,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMessagesRequest {
    #[prost(string, tag = "1")]
    pub chat_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub cursor: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub limit: i32,
    #[prost(string, optional, tag = "4")]
    pub topic_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendMessageRequest {
    #[prost(string, tag = "1")]
    pub chat_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub content_type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub file_metadata_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "5")]
    pub topic_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditMessageRequest {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteMessageRequest {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamRequest {
    #[prost(string, tag = "1")]
    pub chat_id: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamingMessage {
    #[prost(oneof = "streaming_message::Event", tags = "1, 2, 3")]
    pub event: ::core::option::Option<streaming_message::Event>,
}
/// Nested message and enum types in `StreamingMessage`.
pub mod streaming_message {
    #[allow(dead_code)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "1")]
        Message(super::Message),
        #[prost(string, tag = "2")]
        Typing(::prost::alloc::string::String),
        #[prost(string, tag = "3")]
        Presence(::prost::alloc::string::String),
    }
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PinMessageRequest {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    /// true = only for me, false = for everyone
    #[prost(bool, tag = "2")]
    pub personal: bool,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnpinMessageRequest {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub personal: bool,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPinnedMessagesRequest {
    #[prost(string, tag = "1")]
    pub chat_id: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPinnedMessagesResponse {
    #[prost(message, repeated, tag = "1")]
    pub pinned_messages: ::prost::alloc::vec::Vec<PinnedMessage>,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PinnedMessage {
    #[prost(message, optional, tag = "1")]
    pub message: ::core::option::Option<Message>,
    #[prost(bool, tag = "2")]
    pub personal: bool,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateThreadRequest {
    /// the message being replied to
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub content: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub content_type: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetThreadRequest {
    #[prost(string, tag = "1")]
    pub thread_id: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetThreadMessagesRequest {
    #[prost(string, tag = "1")]
    pub thread_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub cursor: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Thread {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub chat_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub root_message_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "4")]
    pub reply_count: i32,
    #[prost(string, tag = "5")]
    pub created_at: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateTopicRequest {
    #[prost(string, tag = "1")]
    pub chat_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetTopicsRequest {
    #[prost(string, tag = "1")]
    pub chat_id: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TopicsResponse {
    #[prost(message, repeated, tag = "1")]
    pub topics: ::prost::alloc::vec::Vec<Topic>,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Topic {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub chat_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub created_at: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChatUnreadCount {
    #[prost(string, tag = "1")]
    pub chat_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub count: i32,
    /// RFC3339 timestamp
    #[prost(string, tag = "3")]
    pub last_message_at: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnreadCountsResponse {
    #[prost(message, repeated, tag = "1")]
    pub counts: ::prost::alloc::vec::Vec<ChatUnreadCount>,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarkChatReadRequest {
    #[prost(string, tag = "1")]
    pub chat_id: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarkMessageReadRequest {
    /// Mark this message and all earlier messages as read
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
}
#[allow(dead_code)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendTypingRequest {
    #[prost(string, tag = "1")]
    pub chat_id: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod messaging_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct MessagingClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MessagingClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MessagingClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MessagingClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MessagingClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        pub async fn create_chat(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateChatRequest>,
        ) -> std::result::Result<tonic::Response<super::Chat>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/CreateChat",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "CreateChat"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_chats(
            &mut self,
            request: impl tonic::IntoRequest<super::super::common::Empty>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::Chat>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/GetChats",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "GetChats"));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn get_messages(
            &mut self,
            request: impl tonic::IntoRequest<super::GetMessagesRequest>,
        ) -> std::result::Result<tonic::Response<super::MessagesPage>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/GetMessages",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "GetMessages"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn send_message(
            &mut self,
            request: impl tonic::IntoRequest<super::SendMessageRequest>,
        ) -> std::result::Result<tonic::Response<super::Message>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/SendMessage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "SendMessage"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn stream_messages(
            &mut self,
            request: impl tonic::IntoRequest<super::StreamRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::StreamingMessage>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/StreamMessages",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "StreamMessages"));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn edit_message(
            &mut self,
            request: impl tonic::IntoRequest<super::EditMessageRequest>,
        ) -> std::result::Result<tonic::Response<super::Message>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/EditMessage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "EditMessage"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_message(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteMessageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/DeleteMessage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "DeleteMessage"));
            self.inner.unary(req, path, codec).await
        }
        /// Pinned messages
        pub async fn pin_message(
            &mut self,
            request: impl tonic::IntoRequest<super::PinMessageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/PinMessage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "PinMessage"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn unpin_message(
            &mut self,
            request: impl tonic::IntoRequest<super::UnpinMessageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/UnpinMessage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "UnpinMessage"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_pinned_messages(
            &mut self,
            request: impl tonic::IntoRequest<super::GetPinnedMessagesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPinnedMessagesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/GetPinnedMessages",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "GetPinnedMessages"));
            self.inner.unary(req, path, codec).await
        }
        /// Threads
        pub async fn create_thread(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateThreadRequest>,
        ) -> std::result::Result<tonic::Response<super::Thread>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/CreateThread",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "CreateThread"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_thread(
            &mut self,
            request: impl tonic::IntoRequest<super::GetThreadRequest>,
        ) -> std::result::Result<tonic::Response<super::Thread>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/GetThread",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "GetThread"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_thread_messages(
            &mut self,
            request: impl tonic::IntoRequest<super::GetThreadMessagesRequest>,
        ) -> std::result::Result<tonic::Response<super::MessagesPage>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/GetThreadMessages",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "GetThreadMessages"));
            self.inner.unary(req, path, codec).await
        }
        /// Topics
        pub async fn create_topic(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateTopicRequest>,
        ) -> std::result::Result<tonic::Response<super::Topic>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/CreateTopic",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "CreateTopic"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_topics(
            &mut self,
            request: impl tonic::IntoRequest<super::GetTopicsRequest>,
        ) -> std::result::Result<tonic::Response<super::TopicsResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/GetTopics",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "GetTopics"));
            self.inner.unary(req, path, codec).await
        }
        /// Unread counts
        pub async fn get_unread_counts(
            &mut self,
            request: impl tonic::IntoRequest<super::super::common::Empty>,
        ) -> std::result::Result<
            tonic::Response<super::UnreadCountsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/GetUnreadCounts",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "GetUnreadCounts"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn mark_chat_read(
            &mut self,
            request: impl tonic::IntoRequest<super::MarkChatReadRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/MarkChatRead",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "MarkChatRead"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn mark_all_read(
            &mut self,
            request: impl tonic::IntoRequest<super::super::common::Empty>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/MarkAllRead",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "MarkAllRead"));
            self.inner.unary(req, path, codec).await
        }
        /// Message delivery/read status
        pub async fn mark_message_read(
            &mut self,
            request: impl tonic::IntoRequest<super::MarkMessageReadRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/MarkMessageRead",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "MarkMessageRead"));
            self.inner.unary(req, path, codec).await
        }
        /// Typing indicators
        pub async fn send_typing(
            &mut self,
            request: impl tonic::IntoRequest<super::SendTypingRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/messaging.Messaging/SendTyping",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("messaging.Messaging", "SendTyping"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod messaging_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MessagingServer.
    #[async_trait]
    pub trait Messaging: std::marker::Send + std::marker::Sync + 'static {
        async fn create_chat(
            &self,
            request: tonic::Request<super::CreateChatRequest>,
        ) -> std::result::Result<tonic::Response<super::Chat>, tonic::Status>;
        /// Server streaming response type for the GetChats method.
        type GetChatsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::Chat, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn get_chats(
            &self,
            request: tonic::Request<super::super::common::Empty>,
        ) -> std::result::Result<tonic::Response<Self::GetChatsStream>, tonic::Status>;
        async fn get_messages(
            &self,
            request: tonic::Request<super::GetMessagesRequest>,
        ) -> std::result::Result<tonic::Response<super::MessagesPage>, tonic::Status>;
        async fn send_message(
            &self,
            request: tonic::Request<super::SendMessageRequest>,
        ) -> std::result::Result<tonic::Response<super::Message>, tonic::Status>;
        /// Server streaming response type for the StreamMessages method.
        type StreamMessagesStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::StreamingMessage, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        async fn stream_messages(
            &self,
            request: tonic::Request<super::StreamRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamMessagesStream>,
            tonic::Status,
        >;
        async fn edit_message(
            &self,
            request: tonic::Request<super::EditMessageRequest>,
        ) -> std::result::Result<tonic::Response<super::Message>, tonic::Status>;
        async fn delete_message(
            &self,
            request: tonic::Request<super::DeleteMessageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        >;
        /// Pinned messages
        async fn pin_message(
            &self,
            request: tonic::Request<super::PinMessageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        >;
        async fn unpin_message(
            &self,
            request: tonic::Request<super::UnpinMessageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        >;
        async fn get_pinned_messages(
            &self,
            request: tonic::Request<super::GetPinnedMessagesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPinnedMessagesResponse>,
            tonic::Status,
        >;
        /// Threads
        async fn create_thread(
            &self,
            request: tonic::Request<super::CreateThreadRequest>,
        ) -> std::result::Result<tonic::Response<super::Thread>, tonic::Status>;
        async fn get_thread(
            &self,
            request: tonic::Request<super::GetThreadRequest>,
        ) -> std::result::Result<tonic::Response<super::Thread>, tonic::Status>;
        async fn get_thread_messages(
            &self,
            request: tonic::Request<super::GetThreadMessagesRequest>,
        ) -> std::result::Result<tonic::Response<super::MessagesPage>, tonic::Status>;
        /// Topics
        async fn create_topic(
            &self,
            request: tonic::Request<super::CreateTopicRequest>,
        ) -> std::result::Result<tonic::Response<super::Topic>, tonic::Status>;
        async fn get_topics(
            &self,
            request: tonic::Request<super::GetTopicsRequest>,
        ) -> std::result::Result<tonic::Response<super::TopicsResponse>, tonic::Status>;
        /// Unread counts
        async fn get_unread_counts(
            &self,
            request: tonic::Request<super::super::common::Empty>,
        ) -> std::result::Result<
            tonic::Response<super::UnreadCountsResponse>,
            tonic::Status,
        >;
        async fn mark_chat_read(
            &self,
            request: tonic::Request<super::MarkChatReadRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        >;
        async fn mark_all_read(
            &self,
            request: tonic::Request<super::super::common::Empty>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        >;
        /// Message delivery/read status
        async fn mark_message_read(
            &self,
            request: tonic::Request<super::MarkMessageReadRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        >;
        /// Typing indicators
        async fn send_typing(
            &self,
            request: tonic::Request<super::SendTypingRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::Ack>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct MessagingServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> MessagingServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MessagingServer<T>
    where
        T: Messaging,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/messaging.Messaging/CreateChat" => {
                    #[allow(non_camel_case_types)]
                    struct CreateChatSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::UnaryService<super::CreateChatRequest>
                    for CreateChatSvc<T> {
                        type Response = super::Chat;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateChatRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::create_chat(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateChatSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/messaging.Messaging/GetChats" => {
                    #[allow(non_camel_case_types)]
                    struct GetChatsSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::ServerStreamingService<super::super::common::Empty>
                    for GetChatsSvc<T> {
                        type Response = super::Chat;
                        type ResponseStream = T::GetChatsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::super::common::Empty>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::get_chats(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetChatsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/messaging.Messaging/GetMessages" => {
                    #[allow(non_camel_case_types)]
                    struct GetMessagesSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::UnaryService<super::GetMessagesRequest>
                    for GetMessagesSvc<T> {
                        type Response = super::MessagesPage;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetMessagesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::get_messages(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetMessagesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/messaging.Messaging/SendMessage" => {
                    #[allow(non_camel_case_types)]
                    struct SendMessageSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::UnaryService<super::SendMessageRequest>
                    for SendMessageSvc<T> {
                        type Response = super::Message;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SendMessageRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::send_message(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SendMessageSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/messaging.Messaging/StreamMessages" => {
                    #[allow(non_camel_case_types)]
                    struct StreamMessagesSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::ServerStreamingService<super::StreamRequest>
                    for StreamMessagesSvc<T> {
                        type Response = super::StreamingMessage;
                        type ResponseStream = T::StreamMessagesStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StreamRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::stream_messages(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamMessagesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/messaging.Messaging/EditMessage" => {
                    #[allow(non_camel_case_types)]
                    struct EditMessageSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::UnaryService<super::EditMessageRequest>
                    for EditMessageSvc<T> {
                        type Response = super::Message;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::EditMessageRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::edit_message(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = EditMessageSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/messaging.Messaging/DeleteMessage" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteMessageSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::UnaryService<super::DeleteMessageRequest>
                    for DeleteMessageSvc<T> {
                        type Response = super::super::common::Ack;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteMessageRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::delete_message(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteMessageSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/messaging.Messaging/PinMessage" => {
                    #[allow(non_camel_case_types)]
                    struct PinMessageSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::UnaryService<super::PinMessageRequest>
                    for PinMessageSvc<T> {
                        type Response = super::super::common::Ack;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PinMessageRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::pin_message(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PinMessageSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/messaging.Messaging/UnpinMessage" => {
                    #[allow(non_camel_case_types)]
                    struct UnpinMessageSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::UnaryService<super::UnpinMessageRequest>
                    for UnpinMessageSvc<T> {
                        type Response = super::super::common::Ack;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UnpinMessageRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::unpin_message(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UnpinMessageSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/messaging.Messaging/GetPinnedMessages" => {
                    #[allow(non_camel_case_types)]
                    struct GetPinnedMessagesSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::UnaryService<super::GetPinnedMessagesRequest>
                    for GetPinnedMessagesSvc<T> {
                        type Response = super::GetPinnedMessagesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetPinnedMessagesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::get_pinned_messages(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetPinnedMessagesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/messaging.Messaging/CreateThread" => {
                    #[allow(non_camel_case_types)]
                    struct CreateThreadSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::UnaryService<super::CreateThreadRequest>
                    for CreateThreadSvc<T> {
                        type Response = super::Thread;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateThreadRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::create_thread(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateThreadSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/messaging.Messaging/GetThread" => {
                    #[allow(non_camel_case_types)]
                    struct GetThreadSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::UnaryService<super::GetThreadRequest>
                    for GetThreadSvc<T> {
                        type Response = super::Thread;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetThreadRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::get_thread(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetThreadSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/messaging.Messaging/GetThreadMessages" => {
                    #[allow(non_camel_case_types)]
                    struct GetThreadMessagesSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::UnaryService<super::GetThreadMessagesRequest>
                    for GetThreadMessagesSvc<T> {
                        type Response = super::MessagesPage;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetThreadMessagesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::get_thread_messages(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetThreadMessagesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/messaging.Messaging/CreateTopic" => {
                    #[allow(non_camel_case_types)]
                    struct CreateTopicSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::UnaryService<super::CreateTopicRequest>
                    for CreateTopicSvc<T> {
                        type Response = super::Topic;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateTopicRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::create_topic(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateTopicSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/messaging.Messaging/GetTopics" => {
                    #[allow(non_camel_case_types)]
                    struct GetTopicsSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::UnaryService<super::GetTopicsRequest>
                    for GetTopicsSvc<T> {
                        type Response = super::TopicsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetTopicsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::get_topics(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetTopicsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/messaging.Messaging/GetUnreadCounts" => {
                    #[allow(non_camel_case_types)]
                    struct GetUnreadCountsSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::UnaryService<super::super::common::Empty>
                    for GetUnreadCountsSvc<T> {
                        type Response = super::UnreadCountsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::super::common::Empty>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::get_unread_counts(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetUnreadCountsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/messaging.Messaging/MarkChatRead" => {
                    #[allow(non_camel_case_types)]
                    struct MarkChatReadSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::UnaryService<super::MarkChatReadRequest>
                    for MarkChatReadSvc<T> {
                        type Response = super::super::common::Ack;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MarkChatReadRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::mark_chat_read(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MarkChatReadSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/messaging.Messaging/MarkAllRead" => {
                    #[allow(non_camel_case_types)]
                    struct MarkAllReadSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::UnaryService<super::super::common::Empty>
                    for MarkAllReadSvc<T> {
                        type Response = super::super::common::Ack;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::super::common::Empty>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::mark_all_read(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MarkAllReadSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/messaging.Messaging/MarkMessageRead" => {
                    #[allow(non_camel_case_types)]
                    struct MarkMessageReadSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::UnaryService<super::MarkMessageReadRequest>
                    for MarkMessageReadSvc<T> {
                        type Response = super::super::common::Ack;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MarkMessageReadRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::mark_message_read(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MarkMessageReadSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/messaging.Messaging/SendTyping" => {
                    #[allow(non_camel_case_types)]
                    struct SendTypingSvc<T: Messaging>(pub Arc<T>);
                    impl<
                        T: Messaging,
                    > tonic::server::UnaryService<super::SendTypingRequest>
                    for SendTypingSvc<T> {
                        type Response = super::super::common::Ack;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SendTypingRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Messaging>::send_typing(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SendTypingSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for MessagingServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "messaging.Messaging";
    impl<T> tonic::server::NamedService for MessagingServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
